const fs = require('fs');
const path = require('path');

const tokensDir = path.join(__dirname, '../design tokens');

function flattenTokens(obj, prefix = '') {
  let result = {};
  for (const key in obj) {
    if (typeof obj[key] === 'object' && obj[key] !== null) {
      if ('$value' in obj[key]) {
        result[prefix + key] = obj[key].$value;
      } else {
        Object.assign(result, flattenTokens(obj[key], prefix + key + '-'));
      }
    }
  }
  return result;
}

function resolveReferences(val, flatTokens) {
  if (typeof val !== 'string') return val;
  return val.replace(/\{([^}]+)\}/g, (match, p1) => {
    const refKey = p1.replace(/\./g, '-').toLowerCase();

    let found = null;
    for (const [k, v] of Object.entries(flatTokens)) {
      if (k.toLowerCase() === refKey) found = v;
    }

    if (found !== null) {
      return resolveReferences(found, flatTokens);
    }

    return `var(--${refKey})`;
  });
}

function processFile(filename) {
  const filePath = path.join(tokensDir, filename);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  return flattenTokens(content);
}

function asPx(val) {
  if (typeof val === 'number') return val === 0 ? '0' : `${val}px`;
  if (typeof val === 'string' && /^\d+(\.\d+)?$/.test(val)) {
    return val === '0' ? '0' : `${val}px`;
  }
  return val;
}

const lightColors = processFile('colors.light.json');
const darkColors = processFile('colors.dark.json');
const radius = processFile('radius.json');
const spacing = processFile('spacing.json');
const typoPrim = processFile('typography.primary.json');
const typoSec = processFile('typography.secondary.json');

const allTokens = { ...lightColors, ...radius, ...spacing, ...typoPrim, ...typoSec };

// ---------------------------------------------------------------------------
// 1. src/theme-vars.css — semantic color tokens, light (default) + dark
// ---------------------------------------------------------------------------
let rootLines = [];
let darkLines = [];

for (const [key, val] of Object.entries(lightColors)) {
  if (key.startsWith('color-semantic')) {
    const cssKey = key.toLowerCase().replace('color-semantic-', '');
    const resolvedVal = resolveReferences(val, lightColors);
    rootLines.push(`  --semantic-color-${cssKey}: ${resolvedVal};`);
  }
}

for (const [key, val] of Object.entries(darkColors)) {
  if (key.startsWith('color-semantic')) {
    const cssKey = key.toLowerCase().replace('color-semantic-', '');
    const cleanKey = cssKey.replace('dark-', '');
    const resolvedVal = resolveReferences(val, darkColors);
    darkLines.push(`  --semantic-color-${cleanKey}: ${resolvedVal};`);
  }
}

const themeVarsContent = `/* Auto-generated by scripts/generate-theme.js — do not edit by hand */
:root {
${rootLines.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root {
${darkLines.join('\n')}
  }
}
`;
fs.writeFileSync(path.join(__dirname, '../src/theme-vars.css'), themeVarsContent);
console.log('Successfully generated src/theme-vars.css');

// ---------------------------------------------------------------------------
// 2. src/theme.css — Tailwind v4 CSS-first @theme block
// ---------------------------------------------------------------------------
const lines = [];

// Base color palettes (brand, gray, red, green, amber)
const palettes = {};
for (const [key, val] of Object.entries(lightColors)) {
  if (key.startsWith('color-semantic')) continue;
  const parts = key.split('-');
  if (parts.length >= 3) {
    const palette = parts[1];
    const weight = parts[2];
    if (!palettes[palette]) palettes[palette] = {};
    palettes[palette][weight] = resolveReferences(val, allTokens);
  }
}
for (const [palette, weights] of Object.entries(palettes)) {
  for (const [weight, val] of Object.entries(weights)) {
    lines.push(`  --color-${palette}-${weight}: ${val};`);
  }
}

// Semantic color aliases -> point at theme-vars.css custom properties
for (const key of Object.keys(lightColors)) {
  if (!key.startsWith('color-semantic')) continue;
  const cssKey = key.toLowerCase().replace('color-semantic-', '');
  lines.push(`  --color-${cssKey}: var(--semantic-color-${cssKey});`);
}

// Radius scale
for (const [key, val] of Object.entries(radius)) {
  const cssKey = key.toLowerCase().replace('radius-', '');
  lines.push(`  --radius-${cssKey}: ${asPx(resolveReferences(val, allTokens))};`);
}

// Spacing scale
for (const [key, val] of Object.entries(spacing)) {
  const cssKey = key.toLowerCase().replace('spacing-', '');
  lines.push(`  --spacing-${cssKey}: ${asPx(resolveReferences(val, allTokens))};`);
}

// Typography — grouped into Tailwind v4's --text-<name> / --text-<name>--line-height / etc.
const typographyObj = {};
for (const [key, val] of Object.entries({ ...typoPrim, ...typoSec })) {
  const lowerKey = key.toLowerCase();
  if (!lowerKey.startsWith('text-')) continue;
  const withoutPrefix = lowerKey.slice(5);
  const lastHyphenIndex = withoutPrefix.lastIndexOf('-');
  if (lastHyphenIndex === -1) continue;
  const element = withoutPrefix.substring(0, lastHyphenIndex);
  const prop = withoutPrefix.substring(lastHyphenIndex + 1);
  let resolvedVal = resolveReferences(val, allTokens);
  if (prop === 'size') resolvedVal = asPx(resolvedVal);
  if (!typographyObj[element]) typographyObj[element] = {};
  typographyObj[element][prop] = resolvedVal;
}

const propToVarSuffix = {
  size: '',
  line: '--line-height',
  track: '--letter-spacing',
  weight: '--font-weight',
};
for (const [element, props] of Object.entries(typographyObj)) {
  if (!props.size) continue;
  lines.push(`  --text-${element}: ${props.size};`);
  if (props.line) lines.push(`  --text-${element}--line-height: ${props.line};`);
  if (props.track !== undefined) lines.push(`  --text-${element}--letter-spacing: ${props.track};`);
  if (props.weight) lines.push(`  --text-${element}--font-weight: ${props.weight};`);
}

const themeContent = `/* Auto-generated by scripts/generate-theme.js — do not edit by hand */
@theme {
${lines.join('\n')}
}
`;
fs.writeFileSync(path.join(__dirname, '../src/theme.css'), themeContent);
console.log('Successfully generated src/theme.css');
